// GENERATED by tools/fetch-foods.mjs — do not edit by hand.
//
// Composition from USDA FoodData Central (SR Legacy), fetched 2026-09-04.
// Each entry names the fdcId it came from; `description` is USDA's own, kept
// so a wrong mapping is visible on sight.
//
// Values are per 100 g: macros in grams (energy in kcal), amino acids in mg.
// Real foods vary — these are reference figures, not a measurement of what is
// in your kitchen.

export const FOODS = [
  {
    "id": "spelt-flour",
    "fdcId": 169745,
    "match": ["mąk\\p{L}*\\s+orkiszow", "orkiszow", "spelt"],
    "gramsPerMl": 0.52,
    "description": "Spelt, uncooked",
    "per100g": {
      "kcal": 338,
      "protein": 14.57,
      "fat": 2.43,
      "carbs": 70.19,
      "sugars": 6.82,
      "fiber": 10.7,
      "sodium": 8
    },
    "aa": {
      "his": 360,
      "ile": 552,
      "leu": 1070,
      "lys": 409,
      "thr": 443,
      "trp": 132,
      "val": 681,
      "sulfur": 588,
      "phe_tyr": 1114
    }
  },
  {
    "id": "oats",
    "fdcId": 169705,
    "match": ["płatk\\p{L}*\\s+owsian", "owsian", "\\boats?\\b"],
    "gramsPerMl": 0.36,
    "description": "Oats (Includes foods for USDA's Food Distribution Program)",
    "per100g": {
      "kcal": 389,
      "protein": 16.89,
      "fat": 6.9,
      "carbs": 66.27,
      "sugars": null,
      "fiber": 10.6,
      "sodium": 2
    },
    "aa": {
      "his": 405,
      "ile": 694,
      "leu": 1284,
      "lys": 701,
      "thr": 575,
      "trp": 234,
      "val": 937,
      "sulfur": 720,
      "phe_tyr": 1468
    }
  },
  {
    "id": "almonds",
    "fdcId": 170567,
    "match": ["migdał", "almond"],
    "gramsPerMl": 0.38,
    "description": "Nuts, almonds",
    "per100g": {
      "kcal": 579,
      "protein": 21.15,
      "fat": 49.93,
      "carbs": 21.55,
      "sugars": 4.35,
      "fiber": 12.5,
      "sodium": 1
    },
    "aa": {
      "his": 539,
      "ile": 751,
      "leu": 1473,
      "lys": 568,
      "thr": 601,
      "trp": 211,
      "val": 855,
      "sulfur": 372,
      "phe_tyr": 1582
    }
  },
  {
    "id": "egg",
    "fdcId": 171287,
    "match": ["jajk", "jaj\\b", "\\beggs?\\b"],
    "gramsPerPiece": 50,
    "description": "Egg, whole, raw, fresh",
    "per100g": {
      "kcal": 143,
      "protein": 12.56,
      "fat": 9.51,
      "carbs": 0.72,
      "sugars": 0.37,
      "fiber": 0,
      "sodium": 142
    },
    "aa": {
      "his": 309,
      "ile": 671,
      "leu": 1086,
      "lys": 912,
      "thr": 556,
      "trp": 167,
      "val": 858,
      "sulfur": 652,
      "phe_tyr": 1179
    }
  },
  {
    "id": "milk",
    "fdcId": 171265,
    "match": ["mlek", "\\bmilk\\b"],
    "gramsPerMl": 1.03,
    "description": "Milk, whole, 3.25% milkfat, with added vitamin D",
    "per100g": {
      "kcal": 61,
      "protein": 3.15,
      "fat": 3.25,
      "carbs": 4.8,
      "sugars": 5.05,
      "fiber": 0,
      "sodium": 43
    },
    "aa": {
      "his": 95,
      "ile": 163,
      "leu": 299,
      "lys": 264,
      "thr": 134,
      "trp": 40,
      "val": 206,
      "sulfur": 102,
      "phe_tyr": 322
    }
  },
  {
    "id": "kefir",
    "fdcId": 170904,
    "match": ["kefir"],
    "gramsPerMl": 1.03,
    "description": "Kefir, lowfat, plain, LIFEWAY",
    "per100g": {
      "kcal": 43,
      "protein": 3.79,
      "fat": 1.02,
      "carbs": 4.77,
      "sugars": 4.61,
      "fiber": 0,
      "sodium": 40
    },
    "aa": {}
  },
  {
    "id": "olive-oil",
    "fdcId": 171413,
    "match": ["oliw", "olive oil"],
    "gramsPerMl": 0.91,
    "description": "Oil, olive, salad or cooking",
    "per100g": {
      "kcal": 884,
      "protein": 0,
      "fat": 100,
      "carbs": 0,
      "sugars": 0,
      "fiber": 0,
      "sodium": 2
    },
    "aa": {
      "his": 0,
      "ile": 0,
      "leu": 0,
      "lys": 0,
      "thr": 0,
      "trp": 0,
      "val": 0,
      "sulfur": 0,
      "phe_tyr": 0
    }
  },
  {
    "id": "sugar",
    "fdcId": 169655,
    "match": ["cukier", "cukru", "\\bsugar\\b"],
    "gramsPerMl": 0.85,
    "description": "Sugars, granulated",
    "per100g": {
      "kcal": 387,
      "protein": 0,
      "fat": 0,
      "carbs": 99.98,
      "sugars": 99.8,
      "fiber": 0,
      "sodium": 1
    },
    "aa": {}
  },
  {
    "id": "honey",
    "fdcId": 169640,
    "match": ["mi[oó]d",
      "miodu",
      "honey"
    ],
    "gramsPerMl": 1.42,
    "description": "Honey",
    "per100g": {
      "kcal": 304,
      "protein": 0.3,
      "fat": 0,
      "carbs": 82.4,
      "sugars": 82.12,
      "fiber": 0.2,
      "sodium": 4
    },
    "aa": {
      "his": 1,
      "ile": 8,
      "leu": 10,
      "lys": 8,
      "thr": 4,
      "trp": 4,
      "val": 9,
      "sulfur": 4,
      "phe_tyr": 19
    }
  },
  {
    "id": "dark-chocolate",
    "fdcId": 170273,
    "match": ["czekolad", "chocolate"],
    "description": "Chocolate, dark, 70-85% cacao solids",
    "per100g": {
      "kcal": 598,
      "protein": 7.79,
      "fat": 42.63,
      "carbs": 45.9,
      "sugars": 23.99,
      "fiber": 10.9,
      "sodium": 20
    },
    "aa": {}
  },
  {
    "id": "salt",
    "fdcId": 173468,
    "match": ["\\bsól\\b", "\\bsoli\\b", "\\bsalt\\b"],
    "gramsPerMl": 1.2,
    "description": "Salt, table",
    "per100g": {
      "kcal": 0,
      "protein": 0,
      "fat": 0,
      "carbs": 0,
      "sugars": 0,
      "fiber": 0,
      "sodium": 38758
    },
    "aa": {
      "his": 0,
      "ile": 0,
      "leu": 0,
      "lys": 0,
      "thr": 0,
      "trp": 0,
      "val": 0,
      "sulfur": 0,
      "phe_tyr": 0
    }
  },
  {
    "id": "baking-powder",
    "fdcId": 172804,
    "match": ["proszk\\p{L}*\\s+do\\s+pieczenia", "baking powder"],
    "gramsPerMl": 0.92,
    "description": "Leavening agents, baking powder, double-acting, straight phosphate",
    "per100g": {
      "kcal": 51,
      "protein": 0.1,
      "fat": 0,
      "carbs": 24.1,
      "sugars": 0,
      "fiber": 0.2,
      "sodium": 7893
    },
    "aa": {}
  },
  {
    "id": "baking-soda",
    "fdcId": 175040,
    "match": ["sod\\p{L}*\\s+oczyszczon", "baking soda"],
    "gramsPerMl": 0.92,
    "description": "Leavening agents, baking soda",
    "per100g": {
      "kcal": 0,
      "protein": 0,
      "fat": 0,
      "carbs": 0,
      "sugars": 0,
      "fiber": 0,
      "sodium": 27360
    },
    "aa": {}
  },
  {
    "id": "vanilla",
    "fdcId": 173471,
    "match": ["wanili", "vanilla"],
    "gramsPerMl": 0.88,
    "description": "Vanilla extract",
    "per100g": {
      "kcal": 288,
      "protein": 0.06,
      "fat": 0.06,
      "carbs": 12.65,
      "sugars": 12.65,
      "fiber": 0,
      "sodium": 9
    },
    "aa": {}
  }
];

/// Match patterns are stored as strings so this file stays plain data; they
/// become case-insensitive Unicode regexes here.
export const FOOD_TABLE = FOODS.map((food) => ({
  ...food,
  match: food.match.map((pattern) => new RegExp(pattern, 'iu')),
}));
